// Generated by https://quicktype.io

export interface Login {
    uid: string;
    reputation: number;
    description: string;
    joiningDate: string;
    displayName: string;
    photoURL: null;
    phoneNumber: null;
    email: string;
}
