// Generated by https://quicktype.io

export interface User {
    uid: string;
    reputation: number;
    description: string;
    joiningDate: string;
    displayName: string;
    photoURL: string;
    phoneNumber: string;
    email: string;
    InterestedTag: any[];
    _count: Count;
}

export interface Count {
    Answer: number;
    Question: number;
}
